publishDir = "docs/"
baseURL = "/"
languageCode = "en-us"
title = "Introduction to Kubernetes"
theme = "learn"
canonifyURLs = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "blue"

