version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/docs
    steps:
      - run: apk update && apk add git && apk add make
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production make build